return {
   {
      file="en",
      label="English",
      subtitleActor=en_subtitle_actor,
      characterSet="en",
   },
   {
      file="es-MX",
      label="Español",
      subLabel="(Latin America)",
      subtitleActor=en_subtitle_actor,
      characterSet="en",
   },
   {
      file="fr",
      label="Français",
      subtitleActor=en_subtitle_actor,
      characterSet="en",
   },
   {
      file="jp",
      label="日本語",
      subtitleActor=jp_subtitle_actor,
      characterSet="jp",
      Setup=function(self) self:halign(0):addx(-200) end,
   },
   {
      file="it",
      label="Italiano",
      subtitleActor=en_subtitle_actor,
      characterSet="en",
   },
   {
      file="ru",
      label="Русский",
      subtitleActor=en_subtitle_actor,
      characterSet="en",
   },
   {
      file="zh-HANS",
      label="简体中文",
      subtitleActor=sc_subtitle_actor,
      characterSet="sc",
      Setup=function(self) self:halign(0):addx(-200) end,
   },
   {
      file="zh-HANT",
      label="繁體中文",
      subtitleActor=tc_subtitle_actor,
      characterSet="tc",
      Setup=function(self) self:halign(0):addx(-200) end,
   },
   {
      file="th",
      bakedFile="th/thai-subtitles.png",
      label="ภาษาไทย",
      subtitleActor=th_subtitle_actor,
      characterSet="th",
      -- Setup=function(self) self:halign(0):addx(-200) end,
   },
}